// ChatStore — per-project chat-log persistence (track I, κ-22).
//
// Mirrors ProjectStore (κ-2, D45): the chat log is the cockpit's own
// app-state, NOT an exports/ record — it lives alongside the project
// manifest under the macOS app-data root (@D g_cockpit_isolation
// clause e). One file per project:
//
//   ~/Library/Application Support/lab.dancin.demiurge/projects/
//       <uuid>/chat.json
//
// Honesty (g3): only `.user` / `.assistant` turns round-trip. The
// `.rejected` banner is dropped on save and regenerated by the
// cockpit's over-claim guard on load — the honesty banner always
// derives from the live guard, never a stale disk copy.
//
// DemiurgeCore stays pure Foundation (Package.swift contract).

import Foundation

public enum ChatStore {
    private static func directory(for project: Project) -> URL {
        ProjectStore.projectsRoot
            .appendingPathComponent(project.id.uuidString, isDirectory: true)
    }

    private static func chatURL(for project: Project) -> URL {
        directory(for: project).appendingPathComponent("chat.json")
    }

    private static var encoder: JSONEncoder {
        let enc = JSONEncoder()
        enc.outputFormatting = [.prettyPrinted]
        enc.dateEncodingStrategy = .iso8601
        return enc
    }

    private static var decoder: JSONDecoder {
        let dec = JSONDecoder()
        dec.dateDecodingStrategy = .iso8601
        return dec
    }

    /// Persist user/assistant turns only (g3 — `.rejected` regenerates
    /// via the cockpit guard on load).
    public static func save(_ messages: [ChatMessage], for project: Project) throws {
        let keep = messages.filter { $0.role != .rejected }
        let dir = directory(for: project)
        try FileManager.default.createDirectory(
            at: dir, withIntermediateDirectories: true)
        try encoder.encode(keep).write(to: chatURL(for: project), options: .atomic)
    }

    /// Load a project's chat log (empty on miss / malformed — a
    /// partial read beats a crash).
    public static func load(for project: Project) -> [ChatMessage] {
        guard let data = try? Data(contentsOf: chatURL(for: project)),
              let messages = try? decoder.decode([ChatMessage].self, from: data) else {
            return []
        }
        return messages
    }
}
