// Main composition — sequences each shot back to back. Visual placeholders
// for now; screen recordings + B-roll get composited in post.
//
// Each shot:
//   - Audio mp3 from assets/voice/<id>.mp3 (generated by scripts/generate-voice.ts)
//   - Visual = placeholder card with shot id, narration, subtitle
//   - Capture note in bottom strip (production cue for the screen recording slot)

import { AbsoluteFill, Audio, Sequence, staticFile, useVideoConfig } from "remotion";
import narration from "./content/narration.json";

type Shot = {
  id: string;
  duration_sec: number;
  narration: string;
  subtitle_ko: string;
  capture: string;
};

const palette = {
  bg: "#0a0a0a",
  fg: "#fafafa",
  muted: "#9ca3af",
  accent: "#a855f7", // demiurge purple
  hot: "#facc15", // capture-cue yellow
};

const ShotCard: React.FC<{ shot: Shot; index: number; total: number }> = ({
  shot,
  index,
  total,
}) => {
  return (
    <AbsoluteFill
      style={{
        background: palette.bg,
        color: palette.fg,
        fontFamily:
          'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
        padding: "80px 100px",
      }}
    >
      {/* top strip — shot id + index */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          fontSize: 28,
          color: palette.muted,
          letterSpacing: 2,
        }}
      >
        <span style={{ color: palette.accent }}>{shot.id}</span>
        <span>
          {index + 1} / {total}
        </span>
      </div>

      {/* narration headline */}
      <div
        style={{
          marginTop: 100,
          fontSize: 56,
          lineHeight: 1.25,
          fontWeight: 700,
          maxWidth: "85%",
        }}
      >
        {shot.narration || (
          <span style={{ color: palette.muted }}>(visual-only · evidence montage)</span>
        )}
      </div>

      {/* Korean subtitle */}
      <div
        style={{
          marginTop: 40,
          fontSize: 32,
          color: palette.muted,
          maxWidth: "85%",
        }}
      >
        {shot.subtitle_ko}
      </div>

      {/* bottom cue strip — capture instruction */}
      <div
        style={{
          position: "absolute",
          left: 100,
          right: 100,
          bottom: 80,
          fontSize: 22,
          color: palette.hot,
          borderTop: `1px solid ${palette.hot}40`,
          paddingTop: 16,
        }}
      >
        📸 capture: {shot.capture}
      </div>
    </AbsoluteFill>
  );
};

export const XprizeDemo: React.FC = () => {
  const { fps } = useVideoConfig();
  const shots = narration.shots as Shot[];

  let cursor = 0;
  return (
    <AbsoluteFill style={{ background: palette.bg }}>
      {shots.map((shot, i) => {
        const durationInFrames = Math.max(1, Math.round(shot.duration_sec * fps));
        const from = cursor;
        cursor += durationInFrames;
        const audioPath = `voice/${shot.id}.mp3`;
        const hasNarration = shot.narration.length > 0;
        return (
          <Sequence key={shot.id} from={from} durationInFrames={durationInFrames} name={shot.id}>
            <ShotCard shot={shot} index={i} total={shots.length} />
            {hasNarration && (
              <Audio src={staticFile(audioPath)} volume={1.0} />
            )}
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};
